import gif from "./elements/header/space GIF-source.gif";
import starfield from "./starfield.jpg";
import head_style from "./elements/header/header.css";
import flyCow from "./elements/header/flyCow.js";
import index_style from "./index.css";
import footer_style from "./elements/footer/footer.css";
import main_content_style from "./elements/homeMainContent/homeMainContent.css";
import cow from "./elements/cow/cow.css";
import wav from "./spaceCow.wav";
import credits_style from "./elements/credits/credits.css";
import spiner_style from "./elements/spiner/spiner.css";
import spiner_js from "./elements/spiner/spiner.js";
